# Generated by Django 4.1.7 on 2023-03-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_headline', models.CharField(max_length=50)),
                ('post_text', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='datum zveřejnění')),
                ('img', models.ImageField(default=None, upload_to='images/')),
                ('group', models.CharField(max_length=20)),
            ],
        ),
    ]
