# Generated by Django 4.1.7 on 2023-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_addresss_contacts_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='person',
            field=models.CharField(max_length=500),
        ),
    ]
