# Generated by Django 4.1.7 on 2023-03-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contacts_phone_alter_contacts_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/icons/')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
    ]
