# Generated by Django 4.1.7 on 2023-03-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_socials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
    ]
