# Generated by Django 4.1.7 on 2023-03-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_social_icon_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='icon',
        ),
    ]
