# Generated by Django 4.1.7 on 2023-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_remove_social_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp_name", models.CharField(max_length=10)),
                ("about_video", models.CharField(max_length=2000)),
                ("map", models.CharField(max_length=2000)),
            ],
        ),
    ]
