# Generated by Django 4.1.7 on 2023-03-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_alter_post_post_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="webelement",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
        migrations.AddField(
            model_name="webelement",
            name="comp_logo",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
    ]
