# Generated by Django 4.1.7 on 2023-03-28 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_webelement_banner_webelement_comp_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webelement",
            name="about_video",
        ),
    ]
