# Generated by Django 4.1.7 on 2023-03-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_remove_webelement_about_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="static/"),
        ),
        migrations.AlterField(
            model_name="webelement",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="static/"),
        ),
        migrations.AlterField(
            model_name="webelement",
            name="comp_logo",
            field=models.ImageField(blank=True, null=True, upload_to="static/"),
        ),
    ]
