# Generated by Django 4.1.7 on 2023-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0018_alter_post_post_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Soupiska",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("birthday", models.DateField(verbose_name="Datum narození")),
                ("photo", models.ImageField(upload_to="static/")),
                ("group", models.CharField(max_length=20)),
            ],
        ),
    ]
